/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MailboxMailboxIdRouteImport } from './routes/mailbox.$mailboxId'
import { Route as MailboxMailboxIdIndexRouteImport } from './routes/mailbox.$mailboxId/index'
import { Route as MailboxMailboxIdSearchRouteImport } from './routes/mailbox.$mailboxId/search'
import { Route as MailboxMailboxIdSettingsRouteImport } from './routes/mailbox.$mailboxId/settings'
import { Route as MailboxMailboxIdEmailsFolderRouteImport } from './routes/mailbox.$mailboxId/emails.$folder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxMailboxIdRoute = MailboxMailboxIdRouteImport.update({
  id: '/mailbox/$mailboxId',
  path: '/mailbox/$mailboxId',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxMailboxIdIndexRoute = MailboxMailboxIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MailboxMailboxIdRoute,
} as any)
const MailboxMailboxIdSearchRoute = MailboxMailboxIdSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MailboxMailboxIdRoute,
} as any)
const MailboxMailboxIdSettingsRoute =
  MailboxMailboxIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => MailboxMailboxIdRoute,
  } as any)
const MailboxMailboxIdEmailsFolderRoute =
  MailboxMailboxIdEmailsFolderRouteImport.update({
    id: '/emails/$folder',
    path: '/emails/$folder',
    getParentRoute: () => MailboxMailboxIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mailbox/$mailboxId': typeof MailboxMailboxIdRouteWithChildren
  '/mailbox/$mailboxId/search': typeof MailboxMailboxIdSearchRoute
  '/mailbox/$mailboxId/settings': typeof MailboxMailboxIdSettingsRoute
  '/mailbox/$mailboxId/': typeof MailboxMailboxIdIndexRoute
  '/mailbox/$mailboxId/emails/$folder': typeof MailboxMailboxIdEmailsFolderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mailbox/$mailboxId/search': typeof MailboxMailboxIdSearchRoute
  '/mailbox/$mailboxId/settings': typeof MailboxMailboxIdSettingsRoute
  '/mailbox/$mailboxId': typeof MailboxMailboxIdIndexRoute
  '/mailbox/$mailboxId/emails/$folder': typeof MailboxMailboxIdEmailsFolderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mailbox/$mailboxId': typeof MailboxMailboxIdRouteWithChildren
  '/mailbox/$mailboxId/search': typeof MailboxMailboxIdSearchRoute
  '/mailbox/$mailboxId/settings': typeof MailboxMailboxIdSettingsRoute
  '/mailbox/$mailboxId/': typeof MailboxMailboxIdIndexRoute
  '/mailbox/$mailboxId/emails/$folder': typeof MailboxMailboxIdEmailsFolderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mailbox/$mailboxId'
    | '/mailbox/$mailboxId/search'
    | '/mailbox/$mailboxId/settings'
    | '/mailbox/$mailboxId/'
    | '/mailbox/$mailboxId/emails/$folder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mailbox/$mailboxId/search'
    | '/mailbox/$mailboxId/settings'
    | '/mailbox/$mailboxId'
    | '/mailbox/$mailboxId/emails/$folder'
  id:
    | '__root__'
    | '/'
    | '/mailbox/$mailboxId'
    | '/mailbox/$mailboxId/search'
    | '/mailbox/$mailboxId/settings'
    | '/mailbox/$mailboxId/'
    | '/mailbox/$mailboxId/emails/$folder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MailboxMailboxIdRoute: typeof MailboxMailboxIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailbox/$mailboxId': {
      id: '/mailbox/$mailboxId'
      path: '/mailbox/$mailboxId'
      fullPath: '/mailbox/$mailboxId'
      preLoaderRoute: typeof MailboxMailboxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailbox/$mailboxId/': {
      id: '/mailbox/$mailboxId/'
      path: '/'
      fullPath: '/mailbox/$mailboxId/'
      preLoaderRoute: typeof MailboxMailboxIdIndexRouteImport
      parentRoute: typeof MailboxMailboxIdRoute
    }
    '/mailbox/$mailboxId/search': {
      id: '/mailbox/$mailboxId/search'
      path: '/search'
      fullPath: '/mailbox/$mailboxId/search'
      preLoaderRoute: typeof MailboxMailboxIdSearchRouteImport
      parentRoute: typeof MailboxMailboxIdRoute
    }
    '/mailbox/$mailboxId/settings': {
      id: '/mailbox/$mailboxId/settings'
      path: '/settings'
      fullPath: '/mailbox/$mailboxId/settings'
      preLoaderRoute: typeof MailboxMailboxIdSettingsRouteImport
      parentRoute: typeof MailboxMailboxIdRoute
    }
    '/mailbox/$mailboxId/emails/$folder': {
      id: '/mailbox/$mailboxId/emails/$folder'
      path: '/emails/$folder'
      fullPath: '/mailbox/$mailboxId/emails/$folder'
      preLoaderRoute: typeof MailboxMailboxIdEmailsFolderRouteImport
      parentRoute: typeof MailboxMailboxIdRoute
    }
  }
}

interface MailboxMailboxIdRouteChildren {
  MailboxMailboxIdSearchRoute: typeof MailboxMailboxIdSearchRoute
  MailboxMailboxIdSettingsRoute: typeof MailboxMailboxIdSettingsRoute
  MailboxMailboxIdIndexRoute: typeof MailboxMailboxIdIndexRoute
  MailboxMailboxIdEmailsFolderRoute: typeof MailboxMailboxIdEmailsFolderRoute
}

const MailboxMailboxIdRouteChildren: MailboxMailboxIdRouteChildren = {
  MailboxMailboxIdSearchRoute: MailboxMailboxIdSearchRoute,
  MailboxMailboxIdSettingsRoute: MailboxMailboxIdSettingsRoute,
  MailboxMailboxIdIndexRoute: MailboxMailboxIdIndexRoute,
  MailboxMailboxIdEmailsFolderRoute: MailboxMailboxIdEmailsFolderRoute,
}

const MailboxMailboxIdRouteWithChildren =
  MailboxMailboxIdRoute._addFileChildren(MailboxMailboxIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MailboxMailboxIdRoute: MailboxMailboxIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
